version: "3.9"

services:
  kepserverbridge:
    image: kepserverbridge
    container_name: kepserverbridge
    network_mode: host
    restart: unless-stopped
    stdin_open: true
    tty: true

    volumes:
      - kepserverbridge-certs:/app/certs

volumes:
  kepserverbridge-certs:

